from django.conf.urls import url

from . import views

app_name = 'crowdclass'
urlpatterns = [ 
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^pretest/$', views.create_user, name='create_user'),
    url(r'^pretest/(?P<pretest_id>[0-9]+)/$', views.pretest, name='pretest'),
    url(r'^posttest/(?P<posttest_id>[0-9]+)/$', views.posttest, name='posttest'),
    url(r'^timesup/$', views.timesup, name='timesup'),
    url(r'^introduction/$', views.introduction, name='introduction'),
    url(r'^(?P<question_id>[0-9]+)/(?P<pid>[0-9]+)/restart/$', views.restart, name='restart'),
    url(r'^(?P<question_id>[0-9]+)/(?P<pid>[0-9]+)/elliptical/$', views.elliptical, name='elliptical'),
    url(r'^(?P<question_id>[0-9]+)/(?P<pid>[0-9]+)/bulge/$', views.bulge, name='bulge'),
    url(r'^(?P<question_id>[0-9]+)/(?P<pid>[0-9]+)/edge/$', views.edge, name='edge'),
    url(r'^(?P<question_id>[0-9]+)/(?P<pid>[0-9]+)/bar/$', views.bar, name='bar'),
    url(r'^(?P<question_id>[0-9]+)/(?P<pid>[0-9]+)/spiral/$', views.spiral, name='spiral'),
    url(r'^(?P<question_id>[0-9]+)/(?P<pid>[0-9]+)/tidal/$', views.tidal, name='tidal'),
    url(r'^(?P<question_id>[0-9]+)/(?P<pid>[0-9]+)/merging/$', views.merging, name='merging'),
    url(r'^(?P<question_id>[0-9]+)/(?P<pid>[0-9]+)/dust/$', views.dust, name='dust'),
    url(r'^(?P<question_id>[0-9]+)/(?P<pid>[0-9]+)/lens/$', views.lens, name='lens'),
    url(r'^(?P<question_id>[0-9]+)/(?P<pid>[0-9]+)/to_elliptical/$', views.to_elliptical, name='to_elliptical'),
    url(r'^(?P<question_id>[0-9]+)/(?P<pid>[0-9]+)/to_bulge/$', views.to_bulge, name='to_bulge'),
    url(r'^(?P<question_id>[0-9]+)/(?P<pid>[0-9]+)/to_edge/$', views.to_edge, name='to_edge'),
    url(r'^(?P<question_id>[0-9]+)/(?P<pid>[0-9]+)/to_bar/$', views.to_bar, name='to_bar'),
    url(r'^(?P<question_id>[0-9]+)/(?P<pid>[0-9]+)/to_spiral/$', views.to_spiral, name='to_spiral'),
    url(r'^(?P<question_id>[0-9]+)/(?P<pid>[0-9]+)/to_tidal/$', views.to_tidal, name='to_tidal'),
    url(r'^(?P<question_id>[0-9]+)/(?P<pid>[0-9]+)/to_merging/$', views.to_merging, name='to_merging'),
    url(r'^(?P<question_id>[0-9]+)/(?P<pid>[0-9]+)/to_dust/$', views.to_dust, name='to_dust'),
    url(r'^(?P<question_id>[0-9]+)/(?P<pid>[0-9]+)/to_lens/$', views.to_lens, name='to_lens'),
    url(r'^(?P<question_id>[0-9]+)/(?P<pid>[0-9]+)/to_elliptical_description/$', views.to_elliptical_description, name='to_elliptical_description'),
    url(r'^hint/(?P<qid>[0-9]+)/(?P<dest>.+)/(?P<pid>[0-9]+)/$', views.hint, name='hint'),
    url(r'^examples_parent/(?P<pid>[0-9]+)/$', views.ex_parents, name='ex_parents'),
    url(r'^examples_round/(?P<pid>[0-9]+)/$', views.ex_round, name='ex_round'),
    url(r'^examples_edge/(?P<pid>[0-9]+)/$', views.ex_edge, name='ex_edge'),
    url(r'^examples_bulge/(?P<pid>[0-9]+)/$', views.ex_bulge, name='ex_bulge'),
    url(r'^examples_bar/(?P<pid>[0-9]+)/$', views.ex_bar, name='ex_bar'),
    url(r'^examples_pattern/(?P<pid>[0-9]+)/$', views.ex_pattern, name='ex_pattern'),
    url(r'^examples_sa/(?P<pid>[0-9]+)/$', views.ex_sa, name='ex_sa'),
    url(r'^examples_sanum/(?P<pid>[0-9]+)/$', views.ex_sanum, name='ex_sanum'),
    url(r'^examples_prominence/(?P<pid>[0-9]+)/$', views.ex_prominence, name='ex_prominence'),
    url(r'^examples_tidal/(?P<pid>[0-9]+)/$', views.ex_tidal, name='ex_tidal'),
    url(r'^examples_odd/(?P<pid>[0-9]+)/$', views.ex_odd, name='ex_odd')
]
