# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdclass', '0003_auto_20160425_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='bardescription',
            name='image',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulgedescription',
            name='image',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dustdescription',
            name='image',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edgedescription',
            name='image',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ellipticaldescription',
            name='image',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lensdescription',
            name='image',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mergingdescription',
            name='image',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spiraldescription',
            name='image',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tidaldescription',
            name='image',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
