# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 03:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdclass', '0008_auto_20160425_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='bar_description',
            new_name='bar_count',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='bulge_description',
            new_name='bulge_count',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='dust_description',
            new_name='dust_count',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='edge_description',
            new_name='edge_count',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='elliptical_description',
            new_name='elliptical_count',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='lens_description',
            new_name='lens_count',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='merging_description',
            new_name='merging_count',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='spiral_description',
            new_name='spiral_count',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='tidal_description',
            new_name='tidal_count',
        ),
    ]
