# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdclass', '0011_auto_20160426_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bardescription',
            name='description_text',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='bulgedescription',
            name='description_text',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='dustdescription',
            name='description_text',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='edgedescription',
            name='description_text',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='lensdescription',
            name='description_text',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='mergingdescription',
            name='description_text',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='tidaldescription',
            name='description_text',
            field=models.CharField(max_length=5000),
        ),
    ]
