# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdclass', '0012_auto_20160426_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ellipticaldescription',
            name='description_text',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='spiraldescription',
            name='description_text',
            field=models.CharField(max_length=5000),
        ),
    ]
