# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdclass', '0014_auto_20160426_0429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_text', models.CharField(max_length=10000)),
                ('difficulty', models.IntegerField(blank=True, null=True)),
                ('score', models.IntegerField(default=2)),
                ('image', models.IntegerField(blank=True, null=True)),
                ('caption', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
