# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 04:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdclass', '0015_introduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='introduction',
            name='score',
        ),
    ]
