# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdclass', '0016_remove_introduction_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='hint',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='bar',
            name='question_text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='bulge',
            name='hint',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='bulge',
            name='question_text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='dust',
            name='hint',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='dust',
            name='question_text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='edge',
            name='hint',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='edge',
            name='question_text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='elliptical',
            name='hint',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='elliptical',
            name='question_text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='lens',
            name='hint',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='lens',
            name='question_text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='merging',
            name='hint',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='merging',
            name='question_text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='spiral',
            name='hint',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='spiral',
            name='question_text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='tidal',
            name='hint',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='tidal',
            name='question_text',
            field=models.CharField(max_length=500),
        ),
    ]
