# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdclass', '0018_auto_20160428_0759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='introduction',
            old_name='description_text',
            new_name='description_text_1',
        ),
        migrations.AddField(
            model_name='introduction',
            name='description_text_2',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='introduction',
            name='description_text_3',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='introduction',
            name='heading',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
